domain_path: C:\Users\oleg.serov\ProjectTutorial1\vitis_ws\zybo_bd\export\zybo_bd\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
